version: '1.0'
services:
  - name: db
    type: postgres
    version: 11.7
    configuration: StandAlone
    username: redmine
    database: redmine
    userPassword: null
    ports:
      - 5432
    remoteAccess: false
    deployTo:
      - redmine

  - name: redmine
    type: docker
    image: redmine
    version: 4
    ports:
      - 3000
    remoteAccess: false
    env:
      REDMINE_DB_POSTGRES: "{{=service('db').getMasterAlias()}}"
      REDMINE_DB_USERNAME: "{{=service('db').get('username')}}"
      REDMINE_DB_DATABASE: "{{=service('db').get('database')}}"
      REDMINE_DB_PASSWORD: "{{=service('db').get('userPassword')}}"
      REDMINE_SECRET_KEY_BASE: "{{=randomString(32)}}"
    deployTo:
      - redmine

  - name: web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: redmine
    deployTo:
      - redmine

hosts:
  - name: redmine
    requirements:
      cores: 1
      memory: 1
